# Generated by Django 4.2 on 2024-07-28 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_1", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proyecto",
            name="imagen",
        ),
        migrations.RemoveField(
            model_name="proyecto",
            name="url",
        ),
    ]
